//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empty_WEB_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_17
    {
        public int Emp_ID { get; set; }
        public string Emp_Name { get; set; }
        public Nullable<decimal> Number { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Blood_group { get; set; }
    }
}
